// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanCandidate } from "./KanCandidate";
import type { Tile } from "./Tile";

/**
 * サーバが提示する、その席がいま取れる操作。
 */
export type ActionOption = { "type": "discard", allowed: Array<Tile>, riichi_allowed: Array<Tile>, } | { "type": "chi", candidates: Array<[Tile, Tile]>, } | { "type": "pon", candidates: Array<[Tile, Tile]>, } | { "type": "kan", candidates: Array<KanCandidate>, } | { "type": "ron" } | { "type": "tsumo" } | { "type": "kyuushu" } | { "type": "pass" };
