// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Liability } from "./Liability";
import type { Meld } from "./Meld";
import type { Seat } from "./Seat";
import type { Tile } from "./Tile";
import type { YakuId } from "./YakuId";

export type AgariResult = { seat: Seat, 
/**
 * ロンなら放銃者、ツモなら None。
 */
from: Seat | null, hand: Array<Tile>, melds: Array<Meld>, win_tile: Tile, yaku: Array<[YakuId, number]>, fu: number, han: number, 
/**
 * 供託と積み棒を含まない素点。
 */
score: number, 
/**
 * 責任払いが成立した場合のみ Some。
 */
liability: Liability | null, 
/**
 * リーチ和了があった場合のみ Some。空配列との使い分けに頼らない。
 */
ura_indicators: Array<Tile> | null, };
