// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tile } from "./Tile";

/**
 * 反応ウィンドウへの応答。使う手牌が曖昧になりうる鳴きは牌を明示する。
 */
export type CallResponse = { "type": "pass" } | { "type": "chi", tiles: [Tile, Tile], } | { "type": "pon", tiles: [Tile, Tile], } | { "type": "kan" } | { "type": "ron" };
