// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientEvent } from "./ClientEvent";

export type ClientEventEnvelope = { seq: number, event: ClientEvent, };
