// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionOption } from "./ActionOption";
import type { AgariResult } from "./AgariResult";
import type { ContinuationReason } from "./ContinuationReason";
import type { DiscardManner } from "./DiscardManner";
import type { DrawSource } from "./DrawSource";
import type { MeldKind } from "./MeldKind";
import type { NextRound } from "./NextRound";
import type { PlayerId } from "./PlayerId";
import type { RiichiStep } from "./RiichiStep";
import type { Round } from "./Round";
import type { Ruleset } from "./Ruleset";
import type { RyuukyokuKind } from "./RyuukyokuKind";
import type { Seat } from "./Seat";
import type { Settlement } from "./Settlement";
import type { Tile } from "./Tile";

export type ClientEvent = { "type": "match_start", players: [PlayerId, PlayerId, PlayerId, PlayerId], rules: Ruleset, you: Seat, } | { "type": "round_start", round: Round, dealer: Seat, honba: number, riichi_sticks: number, scores: [number, number, number, number], seed_commit: string, } | { "type": "deal", your_hand: Array<Tile>, hand_sizes: [number, number, number, number], dora_indicator: Tile, } | { "type": "draw", seat: Seat, 
/**
 * 自席のツモのみ Some。
 */
tile: Tile | null, source: DrawSource, wall_remaining: number, } | { "type": "discard", seat: Seat, tile: Tile, manner: DiscardManner, } | { "type": "riichi", seat: Seat, step: RiichiStep, } | { "type": "call", seat: Seat, from: Seat, kind: MeldKind, tiles: Array<Tile>, } | { "type": "kan_declared", seat: Seat, kind: MeldKind, tile: Tile, } | { "type": "dora_reveal", indicator: Tile, } | { "type": "action_passed", seat: Seat, window_id: number, } | { "type": "agari", results: Array<AgariResult>, settlement: Settlement, } | { "type": "ryuukyoku", kind: RyuukyokuKind, initiator: Seat | null, tenpai: [boolean, boolean, boolean, boolean], 
/**
 * 射影側で公開資格を再判定した結果のみが入る。
 */
revealed_hands: Array<[Seat, Array<Tile>]>, nagashi_winners: Array<Seat>, settlement: Settlement, } | { "type": "round_end", scores: [number, number, number, number], next: NextRound, reason: ContinuationReason, } | { "type": "match_end", final_scores: [number, number, number, number], placements: [number, number, number, number], } | { "type": "request_action", window_id: number, options: Array<ActionOption>, deadline_ms: number, } | { "type": "seed_reveal", seeds: Array<string>, };
