// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallResponse } from "./CallResponse";
import type { Tile } from "./Tile";
import type { TileKind } from "./TileKind";

/**
 * クライアントがサーバへ送れる操作の全て。これ以外は受け付けない。
 */
export type Command = { "type": "discard", tile: Tile, riichi: boolean, } | { "type": "call_response", window_id: number, response: CallResponse, } | { "type": "ankan", kind: TileKind, } | { "type": "kakan", tile: Tile, } | { "type": "tsumo" } | { "type": "kyuushu" };
