// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 局と本場の進み方が決まった理由。エンジンの判断を牌譜から監査するために残す。
 */
export type ContinuationReason = "dealer_win" | "dealer_tenpai" | "dealer_loss" | "abortive_draw" | "nagashi_mangan";
