// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 手出しかツモ切りか。演出と河の表示の双方が必要とするため、
 * 差分からの逆算ではなくイベント自身が持つ。
 */
export type DiscardManner = "tedashi" | "tsumogiri";
