// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 局の進行を止める演出の種類。
 */
export type EffectKind = "draw" | "discard" | "pon" | "chi" | "kan" | "riichi_declare" | "dora_reveal";
