// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiabilityMode } from "./LiabilityMode";
import type { Seat } from "./Seat";
import type { YakuId } from "./YakuId";

/**
 * 責任払い（パオ）。大三元・大四喜の確定牌を鳴かせた者が負う。
 */
export type Liability = { seat: Seat, yaku: YakuId, mode: LiabilityMode, };
