// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeldKind } from "./MeldKind";
import type { Seat } from "./Seat";
import type { Tile } from "./Tile";

/**
 * 副露あるいは暗槓による固定された面子。
 */
export type Meld = { kind: MeldKind, tiles: Array<Tile>, 
/**
 * 鳴いた相手。暗槓は None。
 */
from: Seat | null, 
/**
 * 鳴きの対象になった牌。暗槓は None。
 */
called_tile: Tile | null, };
