// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Round } from "./Round";
import type { Seat } from "./Seat";

export type NextRound = { "type": "next", round: Round, dealer: Seat, honba: number, riichi_sticks: number, } | { "type": "match_over" };
