// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * プレイヤーの識別子。
 *
 * 数値ではなく文字列にする。u64 だと JSON 上は数値になり、JavaScript の
 * `JSON.parse` が安全整数の範囲（2^53）を超えた値を壊す。ID に算術は不要なので、
 * 文字列にしておけばこの種の事故が原理的に起きず、後から UUID へ移っても
 * 契約が変わらない。
 */
export type PlayerId = string;
