// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 宣言（牌を横に倒す）と成立（棒が出て1000点減る）を分ける。
 * 宣言牌そのものは直後の Discard イベントが運ぶ。
 */
export type RiichiStep = "declare" | "accepted";
