// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Wind } from "./Wind";

/**
 * 東1局なら `Round { wind: Wind::East, number: 1 }`。
 */
export type Round = { wind: Wind, number: number, };
