// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchLength } from "./MatchLength";

/**
 * 対局のルール設定。値の変更がコード変更にならないよう、すべてデータとして持つ。
 */
export type Ruleset = { length: MatchLength, start_score: number, return_score: number, uma: [number, number, number, number], red_dora_count: number, kuitan: boolean, double_ron: boolean, formal_tenpai: boolean, noten_penalty: number, nagashi_mangan: boolean, liability: boolean, round_up_mangan: boolean, busted_ends_match: boolean, base_think_ms: number, think_bank_ms: number, network_grace_ms: number, 
/**
 * 打牌から次のツモまでの最短時間。鳴ける者の有無で間の長さが変わると
 * それ自体が情報になるため、常にこの時間だけ待つ。打牌演出と同じ値に揃える。
 */
min_reaction_window_ms: number, };
