// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RyuukyokuKind = "exhaustive" | "nine_terminals" | "four_riichi" | "four_winds" | "four_kans" | "three_rons";
