// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seat } from "./Seat";

/**
 * 点棒移動の内訳。最終差分だけでは、ダブロン時に供託を誰が取ったか、
 * 本場をどちらに付けたかを牌譜から復元できないため分けて持つ。
 */
export type SettlementEntry = { seat: Seat, 
/**
 * 符と翻から決まる素点。
 */
base: number, honba: number, riichi_sticks: number, 
/**
 * 責任払いによる肩代わり分。
 */
liability: number, };
