// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettlementEntry } from "./SettlementEntry";

export type Settlement = { 
/**
 * 各席の最終増減。合計は常に0でなければならない。
 */
delta: [number, number, number, number], entries: Array<SettlementEntry>, };
