// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 成立しうる役とドラの識別子。表示順・翻数は採点側が決める。
 */
export type YakuId = "menzen_tsumo" | "riichi" | "ippatsu" | "chankan" | "rinshan_kaihou" | "haitei_raoyue" | "houtei_raoyui" | "pinfu" | "tanyao" | "iipeiko" | "yakuhai_haku" | "yakuhai_hatsu" | "yakuhai_chun" | "yakuhai_round_wind" | "yakuhai_seat_wind" | "double_riichi" | "chiitoitsu" | "toitoi" | "sanankou" | "sanshoku_doukou" | "sankantsu" | "shousangen" | "honroutou" | "sanshoku_doujun" | "ittsu" | "chanta" | "ryanpeikou" | "junchan" | "honitsu" | "chinitsu" | "tenhou" | "chiihou" | "kokushi_musou" | "kokushi_musou_13" | "suuankou" | "suuankou_tanki" | "daisangen" | "shousuushii" | "daisuushii" | "tsuuiisou" | "ryuuiisou" | "chinroutou" | "chuuren_poutou" | "chuuren_poutou_9" | "suukantsu" | "dora" | "aka_dora" | "ura_dora";
